### Criando usuário
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "silvia",
   "email": "silvia@gmail.com",
   "password": "123456"
}




###  Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "silvia@gmail.com",
   "password": "123456"
}

### Cadastro Partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InNpbHZpYSIsImVtYWlsIjoic2lsdmlhQGdtYWlsLmNvbSIsInJvbGVzIjoiVVNFUiIsImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjVUMDE6NTk6NTYuODMzWiIsInVwZGF0ZUF0IjoiMjAyNC0wNi0yNVQwMTo1OTo1Ni44MzNaIiwiaWF0IjoxNzE5MjgwODQyLCJleHAiOjE3MTkzODA4NDJ9.gc-XgBa5CWDR_tk7KRAAoR1S1IqRT20VIum2LxloXac

{
   "name": "Silvia Madalena e Silva"
   
}



### Cadastro conta
POST http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InNpbHZpYSIsImVtYWlsIjoic2lsdmlhQGdtYWlsLmNvbSIsInJvbGVzIjoiVVNFUiIsImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjVUMDE6NTk6NTYuODMzWiIsInVwZGF0ZUF0IjoiMjAyNC0wNi0yNVQwMTo1OTo1Ni44MzNaIiwiaWF0IjoxNzE5MjgwODQyLCJleHAiOjE3MTkzODA4NDJ9.gc-XgBa5CWDR_tk7KRAAoR1S1IqRT20VIum2LxloXac

{
   "balance": 2000
   
}



###
PATCH  http://localhost:3000/transactions/transfer/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InNpbHZpYSIsImVtYWlsIjoic2lsdmlhQGdtYWlsLmNvbSIsInJvbGVzIjoiVVNFUiIsImNyZWF0ZWRBdCI6IjIwMjQtMDYtMjVUMDE6NTk6NTYuODMzWiIsInVwZGF0ZUF0IjoiMjAyNC0wNi0yNVQwMTo1OTo1Ni44MzNaIiwiaWF0IjoxNzE5MjgwODQyLCJleHAiOjE3MTkzODA4NDJ9.gc-XgBa5CWDR_tk7KRAAoR1S1IqRT20VIum2LxloXac

{
   "balance":100
}