### Criando usuário
POST http://localhost:3000/users
Content-Type: application/json

{
   "name": "marcos",
   "email": "marcos@gmail.com",
   "password": "123456"
}




###  Login
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "marcos@gmail.com",
   "password": "123456"
}

###
@token = {{ loginUser.response.body.access_token }} 


### Cadastro Partner
POST http://localhost:3000/partners
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Marcos Lima da Silva"
   
}



### Cadastro conta
POST http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "balance": 1000
   
}



###
PATCH  http://localhost:3000/transactions/transfer/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "balance":100
}